name: E2E Suite

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/e2e.yml"
      - "lib/**"
      - "proto/**"
      - "scripts/**"
      - "skaffold/**"
      - "src/**"
      - "tests/**"
      - "distribution/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - "build.rs"
      - "docker-compose.yml"
      - "Makefile"
      - "rust-toolchain"
  pull_request: {}
  schedule:
    - cron: "0 4 * * *"

env:
  VERBOSE: true
  RUST_TEST_THREADS: 1
  TEST_LOG: vector=debug
  RUST_BACKTRACE: full
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event_name != 'schedule'
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build-deb-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make package-deb-x86_64
      - uses: actions/upload-artifact@v2
        with:
          name: e2e-test-deb-package
          path: target/artifacts/*
